version: '3.8'

services:
  # Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # depends_on:
    #   - database
    environment:
      DATABASE_URL: mysql://root:mickyoyo12345@database:3306/chomrom_ku
    volumes:
      - ./server:/app/server
      - /server/node_modules


  # MySQL Database
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'chomrom_ku'
      MYSQL_ROOT_PASSWORD: 'mickyoyo12345'
    ports:
      - "3307:3306"
    volumes:
      - ./database:/var/lib/mysql

